services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app/src:/var/www/html/src
      - ./app/tests:/var/www/html/tests

volumes:
  php_socket: